# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloxsmith < Formula
  desc "Bloxsmith — self-contained Infoblox BloxOne NOC dashboard (embedded UI + API proxy)."
  homepage "https://github.com/holland-built/bloxsmith"
  version "3.63.0"
  license "MIT"

  on_macos do
    url "https://github.com/holland-built/bloxsmith/releases/download/v3.63.0/bloxsmith_3.63.0_macOS_universal.tar.gz"
    sha256 "073a87d7d0cd58f2f46c1d072d2b6f48a4a51571a966dc9dcf5f59b620efe754"

    define_method(:install) do
      bin.install "bloxsmith"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/holland-built/bloxsmith/releases/download/v3.63.0/bloxsmith_3.63.0_linux_amd64.tar.gz"
      sha256 "b0a68681a033c176e5d262f04a5f083a190ff3885ccd4e3be7ec8211dfcad701"
      define_method(:install) do
        bin.install "bloxsmith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/holland-built/bloxsmith/releases/download/v3.63.0/bloxsmith_3.63.0_linux_arm64.tar.gz"
      sha256 "a7b9d785760b7f88da849c32d6a60a120012391a08cd74068baf9782d454adfb"
      define_method(:install) do
        bin.install "bloxsmith"
      end
    end
  end

  def caveats
    <<~EOS
      Start Bloxsmith by running:  bloxsmith
      Then open the dashboard:     http://localhost:8080
      Run it at login in the background:  bloxsmith service install
    EOS
  end

  test do
    system "#{bin}/bloxsmith", "--version"
  end
end
