# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloxsmith < Formula
  desc "Bloxsmith — self-contained Infoblox BloxOne NOC dashboard (embedded UI + API proxy)."
  homepage "https://github.com/holland-built/bloxsmith"
  version "3.27.0"
  license "MIT"

  on_macos do
    url "https://github.com/holland-built/bloxsmith/releases/download/v3.27.0/bloxsmith_3.27.0_macOS_universal.tar.gz"
    sha256 "306d3d6675ed1a17d23d707a469aea697f97d7b7c983e8bfaa1b458fe077b358"

    define_method(:install) do
      bin.install "bloxsmith"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/holland-built/bloxsmith/releases/download/v3.27.0/bloxsmith_3.27.0_linux_amd64.tar.gz"
      sha256 "ecfb24a4e56f4bda45e99ded9197da4c6b9223919eda2965ea58268093072fd0"
      define_method(:install) do
        bin.install "bloxsmith"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/holland-built/bloxsmith/releases/download/v3.27.0/bloxsmith_3.27.0_linux_arm64.tar.gz"
      sha256 "dbd605b7d64d064f5b044d74d6e649d05099f99c8a0f055d12621dba437ba3db"
      define_method(:install) do
        bin.install "bloxsmith"
      end
    end
  end

  def caveats
    <<~EOS
      Start Bloxsmith by running:  bloxsmith
      Then open the dashboard:     http://localhost:8080
      Run it at login in the background:  bloxsmith service install
    EOS
  end

  test do
    system "#{bin}/bloxsmith", "--version"
  end
end
